services:
  db:
    image: postgres:latest
    container_name: postgres-spring-boot
    environment:
      POSTGRES_DB: softwareProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: neophenon!@#
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF8"
      POSTGRES_HOST_AUTH_METHOD: trust
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "postgres" ]
#      interval: 10s
#      retries: 5
#      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"

    networks:
      - db

    restart: unless-stopped

  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/softwareProject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: neophenon!@#
    networks:
      - db
    restart: unless-stopped

networks:
    db:
      driver: bridge

volumes:
  postgres_data: